drop table users if exists;

create table users (
	id bigint generated by default as identity (start with 1),
	first_name varchar(50) not null,
	last_name varchar(50) not null,
	age integer not null,
	primary key (id)
);
