DROP TABLE book IF EXISTS;

CREATE TABLE book (
  id INTEGER NOT NULL IDENTITY,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  isbn VARCHAR(17) NOT NULL,
  author VARCHAR(30) NOT NULL,
  title VARCHAR(50) NOT NULL,
  num_pages INTEGER NOT NULL
);